### ISSUE TITLE
% layer not updating

### ISSUE THREAD

**Issue by ChuckRider** [j7126/OctoPrint-Dashboard#248]
I have started my largest print ever.  The % layer gauge is just staying at 0%.  This hasn't happened with smaller prints.

![image](https://user-images.githubusercontent.com/58782813/103440710-897eb380-4c0d-11eb-8163-91a2506219b2.png)

**Comment by Willmac16** [comment]
I believe this is because the current version of Dashboard pulls the in layer progress from the client side gcode viewer which will not auto open large files.

We plan to move away from the gcode viewer for data in V2 (moving to more dashboard backend data gathering and processing), so this issue will probably not be directly addressed.

**Comment by ChuckRider** [comment]
Cool. Thanks
