### ISSUE TITLE
webcam flip

### ISSUE THREAD

**Issue by tutanra** [j7126/OctoPrint-Dashboard#268]
Webcam settings flip do not start when dashboard is active. I have to deactivate it and activate it to have the webcam flip again. This bug did not appear before the last update.

Appears with UI Customizer and DashBoard together.

Regards.

**Comment by Willmac16** [comment]
Is this the octoprint control tab's webcam or the dashboard webcam?

**Comment by tutanra** [comment]
In control webcam tab the image is correct, webcam is disabled in dashboard settings and /webcam/?action=stream is the problem, doesnt read the init settings, there are a minituare in ui customizer that show flipped also.

When I enable dashboard settings, then, /webcam/?action=strem is ok.

**Comment by Willmac16** [comment]
What do you mean by
> webcam is disabled in dashboard settings and /webcam/?action=stream is the problem

**Comment by tutanra** [comment]
sorry, when I disable the webcam widget in the dashboard settings, the link /webcam/?action=stream is flipped.

**Comment by Willmac16** [comment]
As in, the link url changes to something that does not work or the physical webcam stream is flipped so that it looks backwards?


Thank you for clarifying!

**Comment by tutanra** [comment]
My webcam needs to flip and this is active in settings. When I restart octoprint, the webcam is not flipped so I must to disable and enable to show correctly. Seems that webcam doesnt read the settings, only occurs when dashboard & ui customizer and the webcam widget is disabled. Before this update all was working correctly, I have two servers and both occurs the same.

**Comment by Willmac16** [comment]
Okay, I'll test it out.

**Comment by tutanra** [comment]
Thanks a lot.

**Comment by Willmac16** [comment]
I installed UI-Customizer and tested thing out.

I was able to reproduce the issue you have.

This is with the webcam widget disabled:
![image](https://user-images.githubusercontent.com/27445690/112193470-2590d900-8bc5-11eb-90c8-6739a811aa87.png)

and this is with dashboard as a whole disabled:
![image](https://user-images.githubusercontent.com/27445690/112193956-a223b780-8bc5-11eb-8493-65243ee20b38.png)

I will now try to fix the issue, but I am pretty sure that this is an issue with the UI-Customizer plugin since the control tab webcam view works just fine regardless of the dashboard state.

**Comment by Willmac16** [comment]
Okay, I think I figured out the problem. You can try out the fix by installing dashboard with the url `https://github.com/j7126/OctoPrint-Dashboard/archive/refs/heads/development.zip`

**Comment by tutanra** [comment]
yes, fix now, thanks.

**Comment by LazeMSS** [comment]
@tutanra  will this be released soon?

**Comment by j7126** [comment]
@LazeMSS, I think you may have meant to @ myself or @Willmac16, @tutanra only reported the issue. 

Anyway I had though that this had been released a while ago but i guess not. I will release it now.
